assert - вывод исключения
помогает, когда нужно найти баг в программе

assert func(1,2) == 3.1, ":)"

if __name__ == '__main__': /условие истинно, если программа запускается из интерпретатора

возвращает число типа float

тестовый случай или test case
течтовый набор или test suite
